"""stare watcher: surse publicate si ancore de saptamana

Revision ID: 30a011d6d186
Revises: d9520edd8238
Create Date: 2026-08-03 23:42:24.964604

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30a011d6d186"
down_revision: Union[str, Sequence[str], None] = "d9520edd8238"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ANCORA_SAPTAMANA",
        sa.Column("ID_ANCORA", sa.Integer(), nullable=False),
        sa.Column("AN_UNIV", sa.String(length=9), nullable=False),
        sa.Column("SEMESTRU", sa.Integer(), nullable=False),
        sa.Column("INCEPUT", sa.Date(), nullable=False),
        sa.Column("NUMAR", sa.Integer(), nullable=False),
        sa.Column("PARITATE", sa.String(length=2), nullable=False),
        sa.CheckConstraint("PARITATE IN ('SI','SP')", name="ck_ancora_paritate"),
        sa.PrimaryKeyConstraint("ID_ANCORA"),
        sa.UniqueConstraint("AN_UNIV", "SEMESTRU", "INCEPUT", name="uq_ancora"),
    )
    op.create_table(
        "SURSA_ORAR",
        sa.Column("ID_SURSA", sa.Integer(), nullable=False),
        sa.Column("AN_UNIV", sa.String(length=9), nullable=False),
        sa.Column("SEMESTRU", sa.Integer(), nullable=False),
        sa.Column("FEL", sa.String(length=12), nullable=False),
        sa.Column("URL", sa.String(length=255), nullable=False),
        sa.Column("ACTUALIZAT", sa.DateTime(), nullable=True),
        sa.Column("VERIFICAT_LA", sa.DateTime(), nullable=True),
        sa.Column("INGESTAT_LA", sa.DateTime(), nullable=True),
        sa.CheckConstraint("FEL IN ('grupe','profesori')", name="ck_sursa_fel"),
        sa.CheckConstraint("SEMESTRU IN (1,2)", name="ck_sursa_semestru"),
        sa.PrimaryKeyConstraint("ID_SURSA"),
        sa.UniqueConstraint("AN_UNIV", "SEMESTRU", "FEL", name="uq_sursa"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("SURSA_ORAR")
    op.drop_table("ANCORA_SAPTAMANA")
    # ### end Alembic commands ###
