"""schema initiala

Revision ID: 898de4ac5372
Revises:
Create Date: 2026-08-02 20:37:01.369988

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "898de4ac5372"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "GRUPA",
        sa.Column("ID_GRUPA", sa.Integer(), nullable=False),
        sa.Column("PARINTE", sa.Integer(), nullable=True),
        sa.Column("NUME", sa.String(length=160), nullable=False),
        sa.Column("AN_UNIVERSITAR", sa.String(length=12), nullable=False),
        sa.Column("TIP", sa.String(length=16), nullable=False),
        sa.Column("SLUG", sa.String(length=180), nullable=False),
        sa.Column("SPECIALIZARE", sa.String(length=16), nullable=True),
        sa.Column("AN_STUDIU", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "TIP IN ('specializare','serie','grupa','semigrupa','optional')", name="ck_grupa_tip"
        ),
        sa.ForeignKeyConstraint(["PARINTE"], ["GRUPA.ID_GRUPA"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("ID_GRUPA"),
        sa.UniqueConstraint("SLUG", "AN_UNIVERSITAR", name="uq_grupa_slug_an"),
    )
    with op.batch_alter_table("GRUPA", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_GRUPA_PARINTE"), ["PARINTE"], unique=False)
        batch_op.create_index(batch_op.f("ix_GRUPA_SPECIALIZARE"), ["SPECIALIZARE"], unique=False)
        batch_op.create_index("ix_grupa_tip_an", ["TIP", "AN_UNIVERSITAR"], unique=False)

    op.create_table(
        "MATERIE",
        sa.Column("ID_MATERIE", sa.Integer(), nullable=False),
        sa.Column("NUME", sa.String(length=160), nullable=False),
        sa.Column("SLUG", sa.String(length=180), nullable=False),
        sa.Column("CREDITE", sa.Integer(), nullable=True),
        sa.Column("TIP_MATERIE", sa.String(length=40), nullable=True),
        sa.Column("FORMA_EVALUARE", sa.String(length=40), nullable=True),
        sa.Column("TIP_DISCIPLINA", sa.String(length=40), nullable=True),
        sa.Column("AN", sa.Integer(), nullable=True),
        sa.Column("SEMESTRU", sa.Integer(), nullable=True),
        sa.Column("NR_ORE_C", sa.Integer(), nullable=True),
        sa.Column("NR_ORE_S", sa.Integer(), nullable=True),
        sa.Column("NR_ORE_L", sa.Integer(), nullable=True),
        sa.Column("NR_ORE_P", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("ID_MATERIE"),
        sa.UniqueConstraint("SLUG"),
    )
    op.create_table(
        "PERIOADA",
        sa.Column("ID_PERIOADA", sa.Integer(), nullable=False),
        sa.Column("SEMESTRU", sa.Integer(), nullable=False),
        sa.Column("AN_UNIV", sa.String(length=12), nullable=False),
        sa.CheckConstraint("SEMESTRU IN (1,2)", name="ck_perioada_semestru"),
        sa.PrimaryKeyConstraint("ID_PERIOADA"),
        sa.UniqueConstraint("SEMESTRU", "AN_UNIV", name="uq_perioada"),
    )
    op.create_table(
        "PROFESOR",
        sa.Column("ID_PROFESOR", sa.Integer(), nullable=False),
        sa.Column("NUME", sa.String(length=120), nullable=False),
        sa.Column("TITLU", sa.String(length=40), nullable=True),
        sa.Column("SLUG", sa.String(length=140), nullable=False),
        sa.PrimaryKeyConstraint("ID_PROFESOR"),
        sa.UniqueConstraint("NUME"),
        sa.UniqueConstraint("SLUG"),
    )
    op.create_table(
        "SALA",
        sa.Column("ID_SALA", sa.Integer(), nullable=False),
        sa.Column("NUME", sa.String(length=80), nullable=False),
        sa.Column("SLUG", sa.String(length=90), nullable=False),
        sa.Column("TIP", sa.String(length=16), nullable=False),
        sa.CheckConstraint("TIP IN ('fizica','externa','virtuala')", name="ck_sala_tip"),
        sa.PrimaryKeyConstraint("ID_SALA"),
        sa.UniqueConstraint("NUME"),
        sa.UniqueConstraint("SLUG"),
    )
    op.create_table(
        "ORA",
        sa.Column("ID_ORA", sa.Integer(), nullable=False),
        sa.Column("ID_PROFESOR", sa.Integer(), nullable=True),
        sa.Column("ID_MATERIE", sa.Integer(), nullable=True),
        sa.Column("ID_SALA", sa.Integer(), nullable=True),
        sa.Column("ID_GRUPA", sa.Integer(), nullable=False),
        sa.Column("ID_PERIOADA", sa.Integer(), nullable=False),
        sa.Column("TIP_ORA_MATERIE", sa.String(length=24), nullable=True),
        sa.Column("ORA_INCEPUT", sa.Time(), nullable=False),
        sa.Column("ORA_SFARSIT", sa.Time(), nullable=False),
        sa.Column("ZI_SAPTAMANA", sa.String(length=12), nullable=False),
        sa.Column("FRECVENTA", sa.String(length=4), nullable=True),
        sa.Column("SAPTAMANI", sa.String(length=80), nullable=True),
        sa.Column("SEMIGRUPA", sa.String(length=8), nullable=True),
        sa.Column("SURSA_PAGINA", sa.String(length=60), nullable=True),
        sa.Column("CONFIDENCE", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "FRECVENTA IS NULL OR FRECVENTA IN ('SI','SP')", name="ck_ora_frecventa"
        ),
        sa.CheckConstraint(
            "ZI_SAPTAMANA IN ('Luni','Marti','Miercuri','Joi','Vineri','Sambata','Duminica')",
            name="ck_ora_zi",
        ),
        sa.CheckConstraint("ORA_INCEPUT < ORA_SFARSIT", name="ck_ora_interval"),
        sa.ForeignKeyConstraint(
            ["ID_GRUPA"],
            ["GRUPA.ID_GRUPA"],
        ),
        sa.ForeignKeyConstraint(
            ["ID_MATERIE"],
            ["MATERIE.ID_MATERIE"],
        ),
        sa.ForeignKeyConstraint(
            ["ID_PERIOADA"],
            ["PERIOADA.ID_PERIOADA"],
        ),
        sa.ForeignKeyConstraint(
            ["ID_PROFESOR"],
            ["PROFESOR.ID_PROFESOR"],
        ),
        sa.ForeignKeyConstraint(
            ["ID_SALA"],
            ["SALA.ID_SALA"],
        ),
        sa.PrimaryKeyConstraint("ID_ORA"),
    )
    with op.batch_alter_table("ORA", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ORA_ID_GRUPA"), ["ID_GRUPA"], unique=False)
        batch_op.create_index(batch_op.f("ix_ORA_ID_MATERIE"), ["ID_MATERIE"], unique=False)
        batch_op.create_index(batch_op.f("ix_ORA_ID_PERIOADA"), ["ID_PERIOADA"], unique=False)
        batch_op.create_index(batch_op.f("ix_ORA_ID_PROFESOR"), ["ID_PROFESOR"], unique=False)
        batch_op.create_index(batch_op.f("ix_ORA_ID_SALA"), ["ID_SALA"], unique=False)
        batch_op.create_index(
            "ix_ora_grupa_zi", ["ID_GRUPA", "ZI_SAPTAMANA", "ORA_INCEPUT"], unique=False
        )
        batch_op.create_index(
            "ix_ora_sala_zi", ["ID_SALA", "ZI_SAPTAMANA", "ORA_INCEPUT"], unique=False
        )

    op.create_table(
        "USER",
        sa.Column("ID", sa.Integer(), nullable=False),
        sa.Column("NUME", sa.String(length=120), nullable=False),
        sa.Column("EMAIL", sa.String(length=180), nullable=True),
        sa.Column("PAROLA_HASH", sa.String(length=255), nullable=True),
        sa.Column("ID_GRUPA", sa.Integer(), nullable=True),
        sa.Column("SEMIGRUPA", sa.String(length=8), nullable=True),
        sa.ForeignKeyConstraint(["ID_GRUPA"], ["GRUPA.ID_GRUPA"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("ID"),
        sa.UniqueConstraint("EMAIL"),
    )
    with op.batch_alter_table("USER", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_USER_ID_GRUPA"), ["ID_GRUPA"], unique=False)

    op.create_table(
        "ORA_GRUPA",
        sa.Column("ID_ORA", sa.Integer(), nullable=False),
        sa.Column("ID_GRUPA", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["ID_GRUPA"], ["GRUPA.ID_GRUPA"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ID_ORA"], ["ORA.ID_ORA"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ID_ORA", "ID_GRUPA"),
    )
    op.create_table(
        "USER_OPTIONAL",
        sa.Column("ID_USER", sa.Integer(), nullable=False),
        sa.Column("ID_GRUPA", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["ID_GRUPA"], ["GRUPA.ID_GRUPA"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ID_USER"], ["USER.ID"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ID_USER", "ID_GRUPA"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("USER_OPTIONAL")
    op.drop_table("ORA_GRUPA")
    with op.batch_alter_table("USER", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_USER_ID_GRUPA"))

    op.drop_table("USER")
    with op.batch_alter_table("ORA", schema=None) as batch_op:
        batch_op.drop_index("ix_ora_sala_zi")
        batch_op.drop_index("ix_ora_grupa_zi")
        batch_op.drop_index(batch_op.f("ix_ORA_ID_SALA"))
        batch_op.drop_index(batch_op.f("ix_ORA_ID_PROFESOR"))
        batch_op.drop_index(batch_op.f("ix_ORA_ID_PERIOADA"))
        batch_op.drop_index(batch_op.f("ix_ORA_ID_MATERIE"))
        batch_op.drop_index(batch_op.f("ix_ORA_ID_GRUPA"))

    op.drop_table("ORA")
    op.drop_table("SALA")
    op.drop_table("PROFESOR")
    op.drop_table("PERIOADA")
    op.drop_table("MATERIE")
    with op.batch_alter_table("GRUPA", schema=None) as batch_op:
        batch_op.drop_index("ix_grupa_tip_an")
        batch_op.drop_index(batch_op.f("ix_GRUPA_SPECIALIZARE"))
        batch_op.drop_index(batch_op.f("ix_GRUPA_PARINTE"))

    op.drop_table("GRUPA")
    # ### end Alembic commands ###
