"""denumirea intreaga a materiei, din planul de invatamant

Revision ID: a040eb86e6fa
Revises: 30a011d6d186
Create Date: 2026-08-04 02:54:20.969772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a040eb86e6fa"
down_revision: Union[str, Sequence[str], None] = "30a011d6d186"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("MATERIE", schema=None) as batch_op:
        batch_op.add_column(sa.Column("DENUMIRE", sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("MATERIE", schema=None) as batch_op:
        batch_op.drop_column("DENUMIRE")

    # ### end Alembic commands ###
