"""provenienta OCR: bbox si campuri nesigure

Revision ID: d9520edd8238
Revises: 898de4ac5372
Create Date: 2026-08-03 18:55:18.586814

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9520edd8238"
down_revision: Union[str, Sequence[str], None] = "898de4ac5372"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ORA", schema=None) as batch_op:
        batch_op.add_column(sa.Column("SURSA_BBOX", sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column("CAMPURI_NESIGURE", sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ORA", schema=None) as batch_op:
        batch_op.drop_column("CAMPURI_NESIGURE")
        batch_op.drop_column("SURSA_BBOX")

    # ### end Alembic commands ###
